name: Wine MSYS2 Docker

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: wine-msys2.yml
          workflow_conclusion: success
          branch: master-msys2
          path: /opt
      - name: Build Docker Image
        run: |
          echo _ ls -alh
          ls -alh
          # 
          echo _ pwd
          pwd
          #
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          #
          WD=$(pwd)
          #
          echo _ cd /opt
          cd /opt
          #
          echo _ ls -alh /opt
          ls -alh /opt
          #
          echo _ tree -L 2
          tree -L 2
          #
          echo cd
          cd "Wine Stable"
          #
          echo _ ls -alh
          ls -alh
          #
          echo _ sudo tar -xpf wine-*-custom-amd64.tar.xz
          sudo tar -xpf wine-*-custom-amd64.tar.xz
          #
          echo _ ls -alh
          ls -alh
          # 
          echo _ tree -L 2
          tree -L 2
          #
          echo _ ls -alh $WD/Docker
          ls -alh $WD/Docker
          #
          echo _ $WD/Docker/wine 
          mkdir -p $WD/Docker/wine
          #
          echo _ cp -a wine-9.0-rc1-custom-amd64 $WD/Docker/wine
          cp -a wine-9.0-rc1-custom-amd64 $WD/Docker/wine
          #
          #echo _ mv wine-9.0-rc1-custom-amd64 wine
          #mv wine-9.0-rc1-custom-amd64 wine
          #
          echo _ cd $WD/Docker
          cd $WD/Docker
          #
          echo _ ls -alh
          ls -alh
          #
          echo docker build -t wine .
          docker build -t wine .
      - name: Test Docker Image
        run: |
          docker run wine ls -al /opt
          docker run wine find /opt/wine -iname '*.exe'
          docker run wine find /opt/wine -iname '*wine*'
          echo # wine ping.exe
          docker run wine wine /opt/wine/wine-9.0-rc1-custom-amd64/lib/wine/x86_64-windows/ping.exe
          echo # wine ping.exe
          docker run wine wine /opt/wine/wine-9.0-rc1-custom-amd64/lib/wine/x86_64-windows/ping.exe
          echo # ping.exe
          docker run wine /opt/wine/wine-9.0-rc1-custom-amd64/lib/wine/x86_64-windows/ping.exe
          
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Wine Stable
      #     path: ./*.tar.xz
      #     retention-days: 2
