# This workflow consumes the latest artifact from the wine-msys2.yml workflow.
name: Build and upload WINE-MSYS2 docker image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download wine-msys2 artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: wine-msys2.yml
          workflow_conclusion: success
          branch: master-msys2
          path: /opt

      - name: Build Docker Image
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          #
          echo \# cd Docker
          cd Docker
          #
          echo \# sudo tar -xpf /opt/wine-*-custom-amd64.tar.xz
          sudo tar --extract --preserve-permissions --file /opt/wine-msys2/wine-*-custom-amd64.tar.xz
          #
          echo \# mv wine-*-amd64 wine
          mv wine-*-amd64 wine
          #
          echo \# tree -L 2 wine
          tree -L 2 wine
          #
          # TODO: This prints 32bit for our amd64 build. That is weird, and Docker probably can't run this. (Works for now, as some weird workarounds are done.)
          echo \# file wine/bin/wine64
          file wine/bin/wine64
          #
          echo \# wine/bin/wine64 --help
          wine/bin/wine64 --help
          #
          echo \# wine/bin/wine64 --help
          wine/bin/wine64 --help
          #
          echo docker build -t wine .
          docker build -t wine .
          #
          alias docker_wine='docker run -e WINEDEBUG=-all -v $PWD/msys64:/mnt/ wine /opt/wine/bin/wine64'

      - name: Test if Wine works in the docker image
        run: |
          alias docker_wine='docker run -e WINEDEBUG=-all -v $PWD/msys64:/mnt/ wine /opt/wine/bin/wine64'
          echo \# docker run wine find /opt/wine -iname '*.exe'
          #
          docker run wine find /opt/wine -iname '*.exe'
          #
          echo \# file /opt/wine/bin/wine64
          docker run wine file /opt/wine/bin/wine64
          #
          echo \# docker run -e WINEDEBUG=-all -v $PWD/msys64:/mnt/ wine /opt/wine/bin/wine64 --version
          docker run -e WINEDEBUG=-all -v $PWD/msys64:/mnt/ wine /opt/wine/bin/wine64 --version
          echo \# docker_wine --version
          docker_wine --version
          #
          echo \# docker_wine /opt/wine/lib/wine/x86_64-windows/whoami.exe
          docker_wine /opt/wine/lib/wine/x86_64-windows/whoami.exe

      - name: Test if MSYS2 can be run in the docker image
        run: |
          wget --quiet https://github.com/msys2/msys2-installer/releases/download/2023-10-26/msys2-base-x86_64-20231026.tar.xz
          tar --extract --file msys2-base-x86_64-20231026.tar.xz
          docker_wine --help
          docker_wine /mnt/usr/bin/bash.exe -l -c "echo PWD: $PWD"
          docker_wine /mnt/usr/bin/bash.exe -l -c "pacman --version"

      - name: Test if pacman works on MSYS2
        run: |
          docker_wine /mnt/usr/bin/bash.exe -l -c "pacman --sync --needed --noconfirm bc"
          docker_wine /mnt/usr/bin/bash.exe -l -c "echo 1+2 | bc "

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push docker image to Docker Hub
        run: |
          docker tag wine debuglevel/wine-msys2:latest
          docker push debuglevel/wine-msys2:latest

      # TODO: This belongs into an own Workflow (ideally triggered after this one is finished.)
      - name: Install borg/borgmatic dependencies on MSYS2
        run: |
          docker_wine /mnt/usr/bin/bash.exe -l -c "pacman --sync --needed --noconfirm python python-pip"
          docker_wine /mnt/usr/bin/bash.exe -l -c "pacman --sync --needed --noconfirm git base-devel gcc openssl-devel pkgconf"
          docker_wine /mnt/usr/bin/bash.exe -l -c "pacman --sync --needed --noconfirm openssh ssh-pageant"
          #
          docker_wine /mnt/usr/bin/bash.exe -l -c "which python"
          docker_wine /mnt/usr/bin/bash.exe -l -c "which python3"
          docker_wine /mnt/usr/bin/bash.exe -l -c "python --version"
          docker_wine /mnt/usr/bin/bash.exe -l -c "python3 --version"
          docker_wine /mnt/usr/bin/bash.exe -l -c "which pip"
          docker_wine /mnt/usr/bin/bash.exe -l -c "which pip3"
          #
          docker_wine /opt/wine/bin/wine /mnt/usr/bin/bash.exe -l -c "python -m pip install --upgrade pip setuptools wheel"
      - name: Install borgmatic on MSYS2
        run: |
          # docker run -e WINEDEBUG=-all -v $PWD/msys64:/mnt/ wine /opt/wine/bin/wine /mnt/usr/bin/bash.exe -l -c "SETUPTOOLS_USE_DISTUTILS=stdlib pip install borgmatic==1.8.6"
          docker_wine /opt/wine/bin/wine /mnt/usr/bin/bash.exe -l -c "SETUPTOOLS_USE_DISTUTILS=stdlib pip install 'borgmatic @ git+https://github.com/debuglevel/borgmatic@edd2cceceeeb3984a9d39f41e7cfc6fb6495a21f'"
          docker_wine /opt/wine/bin/wine /mnt/usr/bin/bash.exe -l -c "borgmatic --version"
      - name: Install borg on MSYS2
        run: |
          docker_wine /opt/wine/bin/wine /mnt/usr/bin/bash.exe -l -c "pip install borgbackup==1.2.7"
          docker_wine /opt/wine/bin/wine /mnt/usr/bin/bash.exe -l -c "borg --version"          

      - name: Compress (zstd,5) and upload (to keep.sh) MSYS2+borgmatic
        run: |
          export ZSTD_CLEVEL=5
          export ZSTD_NBTHREADS=4
          tar --create --zstd --file msys2-with-borgmatic.tar.zstd msys64
          ls -alh msys2-with-borgmatic.tar.zstd
          curl --upload-file msys2-with-borgmatic.tar.zstd https://free.keep.sh
