name: Build WINE-MSYS2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # from bootstraps.yml:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Create bootstraps
        run: |
          sudo apt update
          sudo apt install debootstrap perl
          #
          chmod +x create_ubuntu_bootstraps.sh
          sudo ./create_ubuntu_bootstraps.sh

      - name: Build Wine
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          #
          echo \# chmod +x build_wine.sh
          chmod +x build_wine.sh
          #
          EXPERIMENTAL_WOW64=true
          export WINE_VERSION="$(wget -q -O - "https://gitlab.winehq.org/wine/wine/-/raw/stable/VERSION" | tail -c +14)"
          WINE_BRANCH=vanilla ./build_wine.sh
          #
          echo \# ls -alh /home/runner/work/wine-msys2/wine-msys2
          ls -alh /home/runner/work/wine-msys2/wine-msys2
          #
          echo \# tree /home/runner/work/wine-msys2/wine-msys2
          tree -L 2 /home/runner/work/wine-msys2/wine-msys2
          #
          echo \# sha256sum *.tar.xz
          sha256sum *.tar.xz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wine-msys2
          path: ./*.tar.xz
          retention-days: 2

# TODO: If this workflow is successful, it should trigger wine-msys2-docker.yml
