# This workflow consumes the latest artifact from the wine-msys2.yml workflow.
name: Build and upload WINE-MSYS2 docker image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      MSYS2_URL: https://github.com/msys2/msys2-installer/releases/download/2023-10-26/msys2-base-x86_64-20231026.tar.xz
      CUSTOM_SRC_PATH: https://gitlab.winehq.org/jhol/wine.git
      CUSTOM_SRC_BRANCH: msys2-hacks-17   # TODO: I probably want the commit id, not the tip of the branch to have a reproducible build. It's fragile enough already.

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download wine-msys2 artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: wine-msys2.yml
          workflow_conclusion: success
          branch: master-msys2
          path: /opt

      - name: Build Docker Image
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          #
          echo \# cd Docker
          cd Docker
          #
          echo \# sudo tar -xpf /opt/wine-*-amd64.tar.xz
          sudo tar --extract --preserve-permissions --file /opt/wine-msys2/wine-*-amd64.tar.xz
          #
          echo \# mv wine-*-amd64 wine
          mv wine-*-amd64 wine
          #
          echo \# tree -L 2 wine
          tree -L 2 wine
          #
          # TODO: This prints 32bit for our amd64 build. That is weird, and Docker probably can't run this. (Works for now, as some weird workarounds are done.)
          echo \# file wine/bin/wine64
          file wine/bin/wine64
          #
          echo \# wine/bin/wine64 --version
          wine/bin/wine64 --version
          #
          echo \# wine/bin/wine64 --version
          wine/bin/wine64 --version
          #
          echo docker build -t wine .
          docker build -t wine .

      - name: Test if Wine works in the docker image
        run: |
          shopt -s expand_aliases
          alias docker_wine='docker run -e WINEDEBUG=-all -v $PWD/msys64:/mnt/ wine /opt/wine/bin/wine64'
          #
          echo \# mkdir -p msys64
          mkdir -p msys64
          #
          echo \# docker run wine find /opt/wine -iname '*.exe'
          docker run wine find /opt/wine -iname '*.exe'
          #
          echo \# file /opt/wine/bin/wine64
          docker run wine file /opt/wine/bin/wine64
          #
          echo \# docker_wine --version
          docker_wine --version
          #
          echo \# docker_wine /opt/wine/lib/wine/x86_64-windows/whoami.exe
          docker_wine /opt/wine/lib/wine/x86_64-windows/whoami.exe

      - name: Extract MSYS2
        run: |
          echo \# wget --quiet -O msys2.tar.xz $MSYS2_URL
          wget --quiet -O msys2.tar.xz $MSYS2_URL
          #
          echo \# ls -al .
          ls -al .
          #
          echo \# tar --extract --file msys2.tar.xz
          tar --extract --file msys2.tar.xz

      - name: Test MSYS2 with WINE
        run: |
          shopt -s expand_aliases
          alias docker_wine='docker run -e WINEDEBUG=-all -v $PWD/msys64:/mnt/ wine /opt/wine/bin/wine64'
          #
          echo \# docker_wine --version
          docker_wine --version
          #
          echo \# docker_wine /mnt/usr/bin/bash.exe -l -c "pwd"
          docker_wine /mnt/usr/bin/bash.exe -l -c "pwd"
          #
          echo \# docker_wine /mnt/usr/bin/bash.exe -l -c "pacman --version"
          docker_wine /mnt/usr/bin/bash.exe -l -c "pacman --version"

      - name: Test if pacman works on MSYS2
        run: |
          shopt -s expand_aliases
          alias docker_wine='docker run -e WINEDEBUG=-all -v $PWD/msys64:/mnt/ wine /opt/wine/bin/wine64'
          #
          docker_wine /mnt/usr/bin/bash.exe -l -c "pacman --sync --needed --noconfirm bc"
          docker_wine /mnt/usr/bin/bash.exe -l -c "echo 1+2 | bc "

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push docker image to Docker Hub
        run: |
          docker tag wine debuglevel/wine-msys2:${GITHUB_SHA}
          docker push debuglevel/wine-msys2:${GITHUB_SHA}
          docker tag wine debuglevel/wine-msys2:latest
          docker push debuglevel/wine-msys2:latest
