name: Wine MSYS2 Docker

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: wine-msys2.yml
          workflow_conclusion: success
          branch: master-msys2
          path: /opt
      - name: Build Docker Image
        run: |
          echo _ ls -alh
          ls -alh
          # 
          echo _ pwd
          pwd
          #
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          #
          WD=$(pwd)
          #
          echo _ cd /opt
          cd /opt
          #
          echo _ ls -alh /opt
          ls -alh /opt
          #
          echo _ tree -L 2
          tree -L 2
          #
          echo cd
          cd "Wine Stable"
          #
          echo _ ls -alh
          ls -alh
          #
          echo _ sudo tar -xpf wine-*-custom-x86.tar.xz
          sudo tar -xpf wine-*-custom-x86.tar.xz
          #
          echo _ sudo tar -xpf wine-*-custom-amd64.tar.xz
          sudo tar -xpf wine-*-custom-amd64.tar.xz
          #
          echo _ ls -alh
          ls -alh
          # 
          echo _ tree -L 2
          tree -L 2
          #
          echo _ ls -alh $WD/Docker
          ls -alh $WD/Docker
          #
          echo _ $WD/Docker/wine 
          mkdir -p $WD/Docker/wine
          #
          echo _ cp -a wine-9.0-rc1-custom-x86 $WD/Docker/wine
          cp -a wine-9.0-rc1-custom-x86 $WD/Docker/wine
          #
          echo _ cp -a wine-9.0-rc1-custom-amd64 $WD/Docker/wine
          cp -a wine-9.0-rc1-custom-amd64 $WD/Docker/wine
          #
          echo \# find $WD/Docker/wine -name '*wine*'
          find $WD/Docker/wine -name '*wine*'
          #
          file $(which ls)
          file $(which ping) 
          file $(which cat)
          #
          # TODO: This prints 32bit for our amd64 build. That is weird, and Docker probably can't run this.
          echo \# file $WD/Docker/wine/wine-9.0-rc1-custom-.../bin/wine
          file $WD/Docker/wine/wine-9.0-rc1-custom-*/bin/wine
          #
          echo \# $WD/Docker/wine/wine-9.0-rc1-custom-amd64/bin/wine --help
          $WD/Docker/wine/wine-9.0-rc1-custom-amd64/bin/wine --help
          #
          echo \# $WD/Docker/wine/wine-9.0-rc1-custom-x86/bin/wine --help
          $WD/Docker/wine/wine-9.0-rc1-custom-x86/bin/wine --help
          #
          echo _ cd $WD/Docker
          cd $WD/Docker
          #
          echo _ ls -alh
          ls -alh
          #
          echo docker build -t wine .
          docker build -t wine .
      - name: Test Docker Image
        env:
          ACTIONS_STEP_DEBUG: true
        run: |
          #echo docker run wine ls -al /opt
          #docker run wine ls -al /opt
          #
          echo \# docker run wine find /opt/wine -iname '*.exe'
          docker run wine find /opt/wine -iname '*.exe'
          #
          #echo \# docker run wine find /opt/wine -iname '*wine*'
          #docker run wine find /opt/wine -iname '*wine*'
          #
          #echo \# docker run wine ls -alh /opt/wine/wine-9.0-rc1-custom-amd64/bin/
          #docker run wine ls -alh /opt/wine/wine-9.0-rc1-custom-amd64/bin/
          #
          echo \# file /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine
          docker run wine file /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine
          #
          echo \# docker run wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine --version
          docker run wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine --version
          #
          echo \# docker run wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /opt/wine/wine-9.0-rc1-custom-amd64/lib/wine/x86_64-windows/whoami.exe
          docker run wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /opt/wine/wine-9.0-rc1-custom-amd64/lib/wine/x86_64-windows/whoami.exe

      - name: Test MSYS2
        env:
          ACTIONS_STEP_DEBUG: true
        run: |
          #echo docker run wine ls -al /opt
          wget https://github.com/msys2/msys2-installer/releases/download/2023-10-26/msys2-base-x86_64-20231026.tar.xz
          tar -xJf msys2-base-x86_64-20231026.tar.xz
          #tree -L 3
          #ls -alh
          #ls -alh msys64
          #docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/msys2.exe
          docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/usr/bin/bash.exe -c "echo HIER: $PWD"
          docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/usr/bin/bash.exe -c "pacman --sync --needed --noconfirm python python-pip"
          docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/usr/bin/bash.exe -c "pacman --sync --needed --noconfirm git base-devel gcc openssl-devel pkgconf"
          docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/usr/bin/bash.exe -c "pacman --sync --needed --noconfirm openssh ssh-pageant"
          docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/usr/bin/bash.exe -c "python -m pip install --upgrade pip setuptools wheel"
          docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/usr/bin/bash.exe -c "python --version"
          docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/usr/bin/bash.exe -c "which python"
          docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/usr/bin/bash.exe -c "which python3"
          docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/usr/bin/bash.exe -c "which pip"
          docker run -v $PWD/msys64:/mnt/ wine /opt/wine/wine-9.0-rc1-custom-amd64/bin/wine /mnt/usr/bin/bash.exe -c "which pip3"
          

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Wine Stable
      #     path: ./*.tar.xz
      #     retention-days: 2
